# Generated by Django 4.0.4 on 2022-05-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "published_at"],
                name="newsfeed_po_status_895d44_idx",
            ),
        ),
    ]
