# Generated by Django 4.0.4 on 2022-05-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0002_post_newsfeed_po_status_895d44_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="newsfeed_po_status_895d44_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status"], name="newsfeed_po_status_d40345_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["published_at"], name="newsfeed_po_publish_38f1e8_idx"
            ),
        ),
    ]
