# Generated by Django 4.0.2 on 2022-03-12 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followtags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_fk', to='newsfeed.tag', unique=True),
        ),
    ]
