# Generated by Django 4.0.4 on 2022-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="name",
            index=models.Index(
                fields=["user_id"], name="user_profil_user_id_22b8a4_idx"
            ),
        ),
    ]
