# Generated by Django 4.0.4 on 2022-05-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_name_user_profil_user_id_22b8a4_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user_id"], name="user_profil_user_id_00bb95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bio",
            index=models.Index(
                fields=["user_id"], name="user_profil_user_id_6ba762_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubaccount",
            index=models.Index(
                fields=["user_id"], name="user_profil_user_id_a2698b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phone",
            index=models.Index(
                fields=["user_id"], name="user_profil_user_id_51841d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skills",
            index=models.Index(
                fields=["user_id"], name="user_profil_user_id_ee1a3c_idx"
            ),
        ),
    ]
